/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: [
      "www.notebookcheck.net",
      "imageio.forbes.com",
      "www.techspot.com",
      "www.cloud.ryanscomputers.com",
      "i.ytimg.com",
      "media.ldlc.com",
      "microless.com",
      "www.techbuy.com.au",
      "i0.wp.com",
      "uk.crucial.com",
      "cdn.mos.cms.futurecdn.net",
      "microless.com",
      "www.teamgroupinc.com",
      "microless.com",
      "m.media-amazon.com",
      "i.rtings.com",
      "www.techporn.ph",
      "m.media-amazon.com",
      "www.startech.com.bd",
      "www.storagereview.com",
      "cdn.mos.cms.futurecdn.net",
      "techplatoon.com.bd",
      "www.custommacbd.com",
      "pcper.com",
      "media.steelseriescdn.com",
      "images.samsung.com",
      "www.crucial.in",
      "images-eu.ssl-images-amazon.com",
      "www.bhphotovideo.com",
      "www.evga.com",
      "www.corsair.com",
      "www.scan.co.uk",
      "www.thermaltake.com",
      "www.bequiet.com",
      "i.dell.com",
      "images.macrumors.com",
      "www.asus.com",
      "www.benq.com",
    ],
  },
};

module.exports = nextConfig;
